Foodbood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts_app_urls'),
    path('', include('home.urls'), name='home_app_urls'),
    path('restaurant/', include('resturants.urls'), name='restaurant_app_urls'),
    path('orders/', include('orders.urls'), name='orders_app_urls'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page_url'),
    path('favoraites/', views.FavPage.as_view(), name='fav_page_url'),
    path('favoraites/delete/<type>/<item_id>/', views.FavDelete.as_view(), name='fav_delete_url'),
    path('favoraites/add/<type>/<item_id>/', views.FavAdd.as_view(), name='fav_add_url'),
    path('setting/', views.SettingPage.as_view(), name='setting_page_url'),
    path('saved_address/', views.SavedAddress.as_view(), name='saved_address_url'),
    path('saved_address/delete/<item_id>/', views.SavedAddressDelete.as_view(), name='saved_address_delete_url'),
    path('saved_address/add/', views.SavedAddressAdd.as_view(), name='saved_address_add_url'),
    path('order_address_add/', views.OrderAddressAdd.as_view(), name='order_address_add_url'),
]

orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.OrdersList.as_view(), name='orders_list_url'),
    path('<order_id>/add_promo/', views.OrdersAddPromo.as_view(), name='order_add_promo_url'),
    path('add_item/<food_id>/', views.OrderItemAdd.as_view(), name='order_add_item_url'),
    path('add_one_item/<food_id>/', views.OrderItemAddOne.as_view(), name='order_add_one_item_url'),
    path('delete_item/<orderitem_id>/', views.OrderItemDelete.as_view(), name='order_delete_item_url'),
    path('checkout/<order_id>/', views.OrderCheckout.as_view(), name='order_checkout_url'),
    path('cancel/<order_id>/', views.OrderCancel.as_view(), name='order_cancel_url'),
]

resturants/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('<rest_id>/', views.RestaurantDetails.as_view(), name='restaurant_detail_url'),
    path('<rest_id>/<category_id>/', views.RestaurantCategoryDetails.as_view(), name='restaurant_category_detail_url'),
]

home/models.py
from django.db import models
from accounts.models import UserTable


class Address(models.Model):
    """
    This is the Model for saving addresses in a user profile
    """
    user = models.ForeignKey(UserTable, on_delete=models.CASCADE, related_name='fav_addr')
    address = models.CharField(max_length=500, null=False, blank=False, default='Isfahan')

    class Meta:
        unique_together = ['user', 'address']

    def __str__(self):
        return self.address

orders/models.py
from django.db import models
from accounts.models import UserTable
from resturants.models import Restaurant
from foods.models import Food
from django.core.validators import MinValueValidator
from django.db.models.signals import pre_save, post_save, post_delete
from django.dispatch import receiver


class Order(models.Model):
    user = models.ForeignKey(UserTable, on_delete=models.CASCADE, related_name='orders')
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='orders')

    price = models.DecimalField(default=0, decimal_places=2, max_digits=10, null=False, blank=True,
                                validators=[MinValueValidator(0)])

    final_price = models.DecimalField(default=0, decimal_places=2, max_digits=10, validators=[MinValueValidator(0)],
                                      null=False, blank=True)

    promo_code = models.CharField(max_length=8, null=True, blank=True)

    status_choices = (
        ('1', 'Cart'),
        ('2', 'Up Coming'),
        ('3', 'Completed'),
        ('4', 'Canceled')
    )

    status = models.CharField(max_length=1, default='1', choices=status_choices, null=False, blank=False)
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (str(self.id) + ":" + self.user.name + ":" + self.restaurant.name + ":"
                + str(self.time.month) + "-" + str(self.time.day))


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    food = models.ForeignKey(Food, on_delete=models.CASCADE, related_name='order_items')
    num = models.IntegerField(default=1, null=False, blank=False, validators=[MinValueValidator(1)])
    price = models.FloatField(default=0, null=False, blank=True, validators=[MinValueValidator(0)])

    def __str__(self):
        return str(self.order.id) + ":" + self.food.name


@receiver([pre_save], sender=OrderItem)
def update_orderitem_price(sender, instance, **kwargs):
    food = instance.food
    instance.price = food.price * instance.num


@receiver([post_save, post_delete], sender=OrderItem)
def update_order_price_caller(sender, instance, **kwargs):
    instance.order.save()


@receiver([pre_save], sender=Order)
def update_order_price(sender, instance, **kwargs):
    try:
        order_items = instance.items.all()
    except Exception:
        instance.price = 0
        instance.final_price = 0
        return

    price = 0
    for item in order_items:
        price += item.price

    instance.price = price
    instance.final_price = price if not instance.promo_code else price - 0.1 * price

resturants/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Restaurant(models.Model):
    name = models.CharField(max_length=256, unique=True)
    restaurant_icon = models.ImageField(null=True, blank=True, upload_to="resturants/static/resturant_icons/")
    restaurant_header_pic = models.ImageField(null=True, blank=True, upload_to="resturants/static/resturant_header_pics/")

    description = models.TextField(null=True, blank=True)
    rating = models.FloatField(default=0.0, validators=[MinValueValidator(0), MaxValueValidator(5)])
    num_rating = models.IntegerField(default=0, validators=[MinValueValidator(0)])

    res_class_chioces = (
        ('1', '$'),
        ('2', '$$'),
        ('3', '$$$')
    )
    restaurant_class = models.CharField(max_length=1, choices=res_class_chioces)
    address = models.CharField(max_length=500, null=False, default="Isfahan")

    free_delivery = models.BooleanField(default=True)

    categ = models.CharField(max_length=32, default="Burger", null=False, blank=False)

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from .models import Address


class AddressCreateForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['address']


class AddressForm(forms.Form):
    address = forms.CharField(max_length=256)

orders/forms.py
from django import forms
from .models import Order, OrderItem


class PromoCodeForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['promo_code']
        labels = {
            'promo_code': 'promo'
        }


class OrderItemAddForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['num']

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden, Http404
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Address
from resturants.models import Restaurant
from foods.models import Food
from django.contrib import messages
from .forms import AddressCreateForm, AddressForm
from accounts.forms import UserInfoUpdateForm


class HomePage(View):
    """
    This is the Basic Class for Handling User MainPage
    """
    def get(self, request):
        if request.user.is_authenticated:
            context = {
                'rests': Restaurant.objects.all(),
                'foods': Food.objects.all()
            }
            return render(request, template_name="home.html", context=context)
        else:
            messages.error(request, 'Please Login to use our site.')
            return redirect('account_login_url')


class SettingPage(LoginRequiredMixin, View):
    """
    This is the basic class for showing the setting page.
    """
    def get(self, request):
        context = {
            'user_form': UserInfoUpdateForm(instance=request.user),
            'address_form': AddressCreateForm()
        }
        return render(request, template_name='setting.html', context=context)


class FavPage(LoginRequiredMixin, View):
    """
    This is the View for handling the Favorates Page
    """
    def get(self, request):
        return render(request, template_name='favorite.html')


class FavDelete(LoginRequiredMixin, View):
    """
    This is a class view for managing the user favorites delete.
    """
    def get(self, request, type, item_id):
        user = request.user
        if type == 'restaurant':
            try:
                rest = Restaurant.objects.get(id=item_id)
                user.fav_rest.remove(rest)
            except Restaurant.DoesNotExist:
                messages.error(request, 'Restaurant Not Found!')
                return redirect('fav_page_url')
            messages.success(request, 'Restaurant Removed Successfully!')
            return redirect('fav_page_url')
        elif type == 'Food':
            try:
                food = Food.objects.get(id=item_id)
                user.fav_food.remove(food)
            except Food.DoesNotExist:
                messages.error(request, 'Food Not Found!')
                return redirect('fav_page_url')
            messages.success(request, 'Food Removed Successfully!')
            return redirect('fav_page_url')
        else:
            return Http404(request)


class FavAdd(LoginRequiredMixin, View):
    """
    This is a class view for managing the user favorites add.
    """
    def get(self, request, type, item_id):
        user = request.user
        if type == 'restaurant':
            try:
                rest = Restaurant.objects.get(id=item_id)
                user.fav_rest.add(rest)
            except Restaurant.DoesNotExist:
                messages.error(request, 'Restaurant Not Found!')
                return redirect('fav_page_url')
            messages.success(request, 'Restaurant Added Successfully!')
            return redirect('fav_page_url')
        elif type == 'Food':
            try:
                food = Food.objects.get(id=item_id)
                user.fav_food.add(food)
            except Food.DoesNotExist:
                messages.error(request, 'Food Not Found!')
                return redirect('fav_page_url')
            messages.success(request, 'Food Added Successfully!')
            return redirect('fav_page_url')
        else:
            return Http404(request)


class SavedAddress(LoginRequiredMixin, View):
    """
    This is the View for handling the Saved Addresses
    """
    def get(self, request):
        user = request.user
        fav_addr = user.fav_addr.all()

        context = {
            'fav_addr': fav_addr,
        }

        return render(request, template_name='Fav_Address_Page.html', context=context)


class SavedAddressDelete(LoginRequiredMixin, View):
    """
    This is a class view for managing the user address delete.
    """
    def get(self, request, item_id):
        user = request.user
        try:
            addr = Address.objects.get(id=item_id)
            if user == addr.user:
                addr.delete()
            else:
                return HttpResponseForbidden(request)
        except Address.DoesNotExist:
            messages.error(request, 'Address Not Found!')
            return redirect('setting_page_url')
        messages.success(request, 'Address Removed Successfully!')
        return redirect('setting_page_url')


class SavedAddressAdd(LoginRequiredMixin, View):
    """
    This is a class view for managing the user address delete.
    """
    def post(self, request):
        user = request.user
        form = AddressCreateForm(request.POST)
        if form.is_valid():
            addr = form.instance
            addr.user = user
            addr.save()
            messages.success(request, "The Address Saved Successfully!")
            return redirect('setting_page_url')

        messages.error(request, "The Address is invalid!")
        return redirect('setting_page_url')

    def get(self, request):
        form = AddressCreateForm()
        return render(request, template_name='Temp_Create_Address.html', context={'form': form})


class OrderAddressAdd(LoginRequiredMixin, View):
    """
    This is a class view for managing the user order address.
    """
    def post(self, request):
        user = request.user
        form = AddressForm(request.POST)
        if form.is_valid():
            user.order_address = form.cleaned_data['address']
            user.save()
            messages.success(request, "The Address Saved Successfully!")
            return redirect('home_page_url')

        messages.error(request, "The Address is invalid!")
        return redirect('home_page_url')

resturants/views.py
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from . models import Restaurant
from foods.models import Category


class RestaurantDetails(LoginRequiredMixin, DetailView):
    model = Restaurant
    template_name = 'resturant.html'
    context_object_name = 'rest'
    pk_url_kwarg = 'rest_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rest = self.get_object()
        foods = rest.foods.all()
        categs = rest.categories.all()
        context['foods'] = foods
        context['categs'] = categs
        context['active_categ'] = 'All'
        return context


class RestaurantCategoryDetails(LoginRequiredMixin, DetailView):
    model = Restaurant
    template_name = 'restaurant_detail_page.html'
    context_object_name = 'rest'
    pk_url_kwarg = 'rest_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rest = self.get_object()
        category_id = self.kwargs['category_id']
        active_category = Category.objects.get(id=category_id)
        foods = active_category.foods.all()
        categs = rest.categories.all()
        context['foods'] = foods
        context['categs'] = categs
        context['active_categ'] = active_category
        return context

templates/base_html.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'pics/Icon copy.png' %}">
    <link rel="stylesheet" href="{% static 'css/home-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/card.css' %}">
    {% block css_js_ref %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">


    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<div class="d-flex flex-row">
    <div class="d-flex flex-column justify-content-between nibble-container" style="min-height: 100vh;">
        <div class="d-flex flex-column justify-content-start ">
            <div class="d-flex flex-row ms-4 mt-3 align-items-center ">
                <img src="{% static 'pics/Icon copy.png' %}" alt="burger">
                <p class="ms-3 mt-3">
                    FoodBood
                </p>
            </div>
            <div class="ms-4">
                <div id="my_btn" class="mt-4 left-menu">
                    <img src="../../static/pics/Home.png">
                    <a class="ms-3 link-adjustment" href="{% url 'home_page_url' %}">Home</a>
                </div>
                <div id="my_btn2" class="mt-4 left-menu">
                    <img src="../../static/pics/Feed copy.png">
                    <a class="ms-3 link-adjustment" href="{% url 'home_page_url' %}">Explore</a>
                </div>
                <div id="my_btn3" class="mt-4 left-menu">
                    <img src="../../static/pics/save copy.png">
                    <a class="ms-3 link-adjustment" href="{% url 'fav_page_url' %}">Favourites</a>
                </div>
                <div id="my_btn4" class="mt-4 left-menu" onclick="goTo_orders();">
                    <img src="../../static/pics/Document copy.png">
                    <a class="ms-3 link-adjustment" href="{% url 'orders_list_url' %}">orders</a>
                </div>
                <div id="my_btn5" class="mt-4 left-menu">
                    <img src="../../static/pics/Settings copy.png">
                    <a class="ms-3 link-adjustment" href="{% url 'setting_page_url' %}">settings</a>
                </div>

            </div>
        </div>
        <div class="d-flex flex-row justify-content-between align-items-center clarke-div">
            <img class="mark-clarke" src="{{ user.profile_pic.url }}">
            <p>
                <b>{{ user.name }}</b>
                <br>
                {{ user.email }}
            </p>
            <img class="options" src="../../static/pics/Options copy.png">
        </div>
    </div>
    <div class="class=d-flex flex-column justify-content-center align-items-center  rightmost-div"
         style="padding: 32px;">
        <div class="col-lg-6 d-none d-lg-block" style="width: 100%;">
            <div class="d-flex flex-row navbar align-items-center justify-content-between ">
                <div class="d-flex flex-row">
                    <div class="d-flex flex-row align-items-center nav-margin"><img class="img-size"
                                                                                    src="../../static/pics/Location copy.png">
                        <p class="fs-one ms-3 m-0 text-center text-nowrap">San Francisco, California</p><img
                                class="arrow-size ms-3" src="../../static/pics/Options copy.png"></div>
                    <div class="d-flex flex-row align-items-center nav-margin"><img class="img-size"
                                                                                    src="../../static/pics/Shopping-bag copy.png">
                        <p class="fs-one m-0 ms-3 text-center text-nowrap">Pick up</p><img class="arrow-size ms-3"
                                                                                           src="../../static/pics/Options copy.png">
                    </div>
                    <div class="d-flex flex-row align-items-center nav-margin"><img class="img-size"
                                                                                    src="../../static/pics/Icon copy 2.png">
                        <p p class="fs-one ms-3 m-0 text-center text-nowrap">best deals</p><img class="arrow-size ms-3 "
                                                                                                src="../../static/pics/Options copy.png">
                    </div>

                </div>
                <div class="d-flex search-margin">
                    <div class="relative-search">
                        <img class="search-icon" src="../../static/pics/Search.png">
                        <input type="search" class="search-container nav-margin" id="search" name="search"
                               placeholder="search for anything...">
                    </div>
                </div>
                <div class=" d-flex justify-content-between "><img src="../../static/pics/48px copy.png">
                    <img data-toggle="modal" data-target="#FoodCard" class="cart-container" src="../../static/pics/cart copy.png"></div>

            </div>
        </div>
        <div class="col-12 d-sm-block d-lg-none">
            <div class=" d-flex justify-content-between ">
                <div>
                </div>
                <div><img src="../../static/pics/48px copy.png"><img class="cart-container" src="../../static/pics/cart copy.png">
                </div>
            </div>
        </div>
        {% block main %}
        {% endblock %}
        <div class="modal" id="FoodCard">
            <div class="Card">
                <div class="d-flex flex-row justify-content-between w-100">
                    <div class="card_title">My cart ({{ user.get_user_carts|length }} Carts)</div>
                    <img width="24" height="24" src="../../static/pics/Close.png" data-dismiss="modal">
                </div>
                <div class="d-flex flex-row justify-content-between mt-4">
                    <div>
                        <div class="deliver_title">Deliver to</div>
                        <div class="deliver_address">{{ user.order_address }}</div>
                    </div>
                    <button class="card_btn" data-toggle="modal" data-target="#AddresCard"><img
                            src="../../static/pics/arrow copy.png"></button>
                </div>
                <div>
                    {% for order in user.get_user_carts %}
                    <div>{{ order.restaurant.name}}</div>
                    <div>
                        {% for item in order.items.all %}
                        <div class="d-flex flex-row justify-content-between align-items-center mt-4">
                            <img src="{{ item.food.food_pic.url }}">
                            <div class="d-flex flex-row">
                                <div>{{ item.num }}</div>
                                <div>X</div>
                            </div>
                            <div>
                                <div>{{ item.food.name }}</div>
                                <div>{{ item.price }}</div>
                            </div>
                            <div>
                                <a href="{% url 'order_delete_item_url' item.id %}"><img src="../../static/pics/20px-icon-inside copy 2.svg"/></a>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="d-flex flex-row gap-3">
                            <div>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"
                                     fill="none">
                                    <path d="M16 9.14286H9.14286V16H6.85714V9.14286H0V6.85714H6.85714V0H9.14286V6.85714H16V9.14286Z"
                                          fill="#503E9D"/>
                                </svg>
                            </div>
                            <br>
                            <div class="more_items_text">
                                Add more items
                            </div>
                        </div>
                        <div class="d-flex flex-row m-4">
                            <img src="../../static/pics/Icon-2.svg"/>
                            <div>
                                <div>Delivery </div>
                                <div> $0</div>
                            </div>
                        </div>
                        <div class="d-flex flex-row justify-content-between m-4 w-100 ">
                            <form method="POST" action="{% url 'order_add_promo_url' order.id %}">
                                {% csrf_token %}
                            <img src="../../static/pics/Icon.svg"/>
                            <div>
                                <label for="id_promo_code">Promo code</label>
                                <input name="promo_code" id="id_promo_code" type="text" class="promo_input" placeholder="{{ order.promo_code }}">
                            </div>
                            <input type="image" class="card_btn" src="../../static/pics/20px-icon-inside copy 3.svg" alt="">
                            </form>
                        </div>
                    </div>
                    <div class="d-flex flex-row gap-3">
                        <button class="card_btn">
                            <img src="../../static/pics/Icon copy.svg"/>
                        </button>
                        <a href="{% url 'order_checkout_url' order.id %}"><button class="card_payment">Checkout (${{ order.final_price }})</button></a>
                    </div>
                {% endfor %}
                </div>

            </div>
            <div class="modal" id="AddresCard">
                <div class="w-100 d-flex justify-content-center">
                    <div class="promo_card p-3">
                        <div class="d-flex flex-row justify-content-between w-100">
                            <div class="card_title">Delivery address</div>
                            <img width="24" height="24" src="../../static/pics/Close.png" data-dismiss="modal">
                        </div>
                        <form method="POST" action="{% url 'order_address_add_url' %}">
                            {% csrf_token %}
                            <div class="d-flex flex-column">
                                <label for="ADDress">Address</label>
                                <input type="text" name="address" id="ADDress">
                            <input type="submit" class="promo_btn" value="Confirm">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal" id="PromoCodeCard">
                <div class="w-100 d-flex justify-content-center">
                    <div class="promo_card p-3">
                        <div class="d-flex flex-row justify-content-between w-100">
                            <div class="card_title">Enter promo code</div>
                            <img width="24" height="24" src="../../static/pics/Close.png" data-dismiss="modal">
                        </div>
                        <form>
                            <input class="promo_input" placeholder="HXFWO"/>
                            <button class="promo_btn">Confirm</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% block bottom_of_body %}
{% endblock %}
</html>

templates/favorite.html
{% extends 'base_html.html' %}
{% load static %}

{% block title %}Favorate{% endblock %}
{% block css_js_ref %}
    <link rel="stylesheet" href="{% static 'css/css-home-2.css' %}">
    <link rel="stylesheet" href="{% static 'css/explor.css' %}">
{% endblock %}

{% block left_panel %}
{% endblock %}

{% block main %}
        <div  style="margin-top: 48px;">
            <div  class="d-flex flex-row justify-content-between w-25">
                <button id="rest" class="choice_resturant"><img id="rest_img" src="../../static/pics/super.png"> Restaurants ({{ user.fav_rest.all|length }})</button>
                <button id="dish" class="choice_dish"><img id="dish_img" src="../../static/pics/whiteSilverware.png">Dishes ({{ user.fav_food.all|length }})</button>
            </div>
            <div  id="foods">
                <div  class="container">
                    <div class="row">
                        {% for food in user.fav_food.all %}
                            <div class="col-4">
                                <a href="{% url 'order_add_one_item_url' food.id %}"><img src="{{ food.food_pic.url }}"></a>
                            <div class="d-flex flex-row align-items-center justify-content-between ms-3">
                                <div class="d-flex flex-row grid-img"><img src="../../static/pics/Star.png"><p class="bx-font">
                                    {{ food.rating }} ({{ food.num_rating }})</p></div>
                                <div class="d-flex flex-row grid-img margin-grid"><img  src="../../static/pics/Silverware.png"><p class="bx-font ms-1">
                                    {{ food.category }}</p></div>
                                <div class="d-flex flex-row grid-img margin-grid"><img src="../../static/pics/Deliver.png"><p class="bx-font ms-1">15 - 25 min</p></div>
                                </div>
                            <div  class="d-flex flex-row align-items-center justify-content-between mt-3"><p style="font-size: 16px; font-weight: 700;">{{ food.name }}</p><p class="free-delivery text-center pt-1 ">Free delivery</p></div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div id="resturant_list" class="offDive">
                <div  style="margin-top: 48px;">
                    <div class="container">
                        <div class="row mt-4">
                            {% for rest in user.fav_rest.all %}
                                <div class="d-flex flex-row col-4 features-bx">
                                    <div class="d-flex burger-bg"><a href="{% url 'restaurant_detail_url' rest.id %}"><img class="burgerking" src="{{ rest.restaurant_icon.url }}"></a></div>
                                <div class="d-flex flex-column justify-content-between">
                                    <h5 class="ms-3">{{ rest.name }}</h5>
                                    <div class="d-flex flex-row align-items-center justify-content-between ms-3">
                                    <div class="d-flex flex-row grid-img"><img src="../../static/pics/Star.png"><p class="bx-font">{{ rest.rating }} ({{ rest.num_rating }})</p></div>
                                    <div class="d-flex flex-row grid-img margin-grid"><img src="../../static/pics/Silverware.png"><p class="bx-font ms-1">
                                        {{ rest.categ }}</p></div>
                                    <div class="d-flex flex-row grid-img margin-grid"><img src="../../static/pics/Money.png"><p class="bx-font ms-1">{{ rest.get_restaurant_class_display }}</p></div>
                                    </div>
                                    <div class="d-flex flex-row grid-img ms-3 "><div class="free-delivery" >
                                        {% if rest.free_delivery %}
                                            <p class="bx-font ">Free delivery</p>
                                        {% else %}
                                            <p class="bx-font ">$5.0</p>
                                        {% endif %}</div>
                                        <div class=" d-flex flex-row ms-3"><img src="../../static/pics/Location copy 2.png"><p class="bx-font ms-3">4.3 km</p></div></div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}
{% block bottom_of_body %}
<script src="{% static 'js/home.js' %}"></script>
<script src="{% static 'js/explor.js' %}"></script>
{% endblock %}